import Cocoa

// MARK: - Color Palette (Lumi-style Ragdoll Cat)
enum CatColors {
    static let palette: [NSColor] = [
        .clear,                                // 0 transparent
        NSColor(hex: 0x2E2735)!,               // 1 outline
        NSColor(hex: 0xFFF9EE)!,               // 2 bright fur
        NSColor(hex: 0xF4E8D6)!,               // 3 cream fur
        NSColor(hex: 0xC9B8AA)!,               // 4 soft shadow
        NSColor(hex: 0x8E7A79)!,               // 5 seal point
        NSColor(hex: 0xF7B8BE)!,               // 6 pink
        NSColor(hex: 0x1D5FBF)!,               // 7 deep blue
        NSColor(hex: 0x62A8FF)!,               // 8 light blue
        NSColor(hex: 0xFFFFFF)!,               // 9 highlight
        NSColor(hex: 0xA38F8E)!,               // 10 tail / paw shadow
        NSColor(hex: 0x8B5E73)!,               // 11 mouth accent
    ]
}

// MARK: - Sprite Frame Data
enum SpriteData {
    static let idleTextureNames = (0...11).map { "idle\($0)" }
    static let walkTextureNames = (0...8).map { "walk\($0)" }
    static let sleepTextureNames = (0...3).map { "sleep\($0)" }
    static let wantFishTextureNames = (0...10).map { "wantFish\($0)" }

    private static let map: [Character: Int] = [
        ".": 0,
        "x": 1,
        "w": 2,
        "c": 3,
        "g": 4,
        "s": 5,
        "p": 6,
        "b": 7,
        "i": 8,
        "h": 9,
        "t": 10,
        "m": 11,
    ]

    private static func frame(_ rows: [String]) -> [[Int]] {
        rows.map { row in
            row.map { map[$0, default: 0] }
        }
    }

    private static func frameFlipped(_ rows: [String]) -> [[Int]] {
        frame(rows.reversed())
    }

    // Front sit, eyes open.
    static let idle0 = frameFlipped([
        "..ggwwwwwcpgggtgtggcwwwwpgcwwwwc",
        ".cgmtcwwwpggttggggggwwwptggcwwcg",
        "ctggtpwcgggttgwciitggcwcccccwcgg",
        "wggcccwcgtttgwgiiiittggcwwwcgtti",
        "..ggwwwwpgtstciibbibxttgggggtsxi",
        "..gmgwwwcpgmsgbbxxbbxttttttttsxb",
        ".ctgpcwwwcgmxbbgtxxbxggttttttsxb",
        "..gtcwwwwcgtmxswwmxxsggtttttgtxt",
        "...ggwwwwwcgtsxstxxxtttttttttgsx",
        "...wscwwwwwpgtsxxxxttttttttttttt",
        "....stcwwwwcggtgtttttgtttttttttt",
        "....cxgcwwwwwpggttttgggtttttggtt",
        "...csxsgwwwwwwcpggttgpggttggpgtt",
        "..wmxsssgcwwwwwwcgttpcpggtggppgs",
        "...gmmtmscwwwwwwwggpccppgggpccpg",
        "...txmsstgcwwwwwwcpcccppggpppccp",
        "...tmmmtttpcwwwwwwwwwwcccpcccwww",
        "....mmtgptsgcwwwwwwwwwccccccwwww",
        "....xmgpppsmtccwwwwwwwwwwwwwwwww",
        "....xmgpppggcttcwwwwwwwwwwwwwwww",
        "....xmgppcwwctmgccwwwwwwwwwwwwww",
        "....xmgppgpcctmstgcwwwwwwwwwwwww",
        "....xstgpppcgmsttstcwwwwwwwwwwwg",
        "....xssgppppmmtttxxmtgwcgtgwgttx",
        "....mmsgppptmtttxsccggttggtttggc",
        "....cxstggtsttsxt.....gc..wgc...",
        ".....xsssmmttsxt................",
        ".....xstsmttmmt.................",
        ".....xmttttmxg..................",
        ".....mmttmmgc...................",
        ".....cxxxmc.....................",
        "......cccw......................",
        "................................",
        "................................",
    ])

    // Drowsy glance, tail swings left.
    static let idle1 = frameFlipped([
        "...............cgtmgwwccggtgpccc",
        "...............gtccccwgtttgccibb",
        "................ggcwwwpttsgcitxx",
        ".................ttcwwwgtxstbsxx",
        "................cttpwwwwgmxxxxxx",
        "................ctpwwwwwpgtttttt",
        ".................ggcwwwwcggttttt",
        "..................tgwwwwwcggtttt",
        "..................cmgwwwwwcggttt",
        "...................sxcwwwwwcggtt",
        "..................gmmgcwwwwwccgg",
        ".................cxmtstcwwwwwwcg",
        ".................csxttmpwwwwwwwg",
        ".................wsxmsttcwwwwwww",
        ".................cmmmspsgcwwwwww",
        "..................wxsgpgmtgcwwww",
        "..................cxtppptmtgpwww",
        "..................cxtppcggcgmcww",
        "..................cxtpppcwcgxtgc",
        "..................cxtgppgpcgmttg",
        "..................cxstpppcgmsgts",
        "..................cxmtpppptmggtx",
        "...................gxtgpptmtgtxg",
        "...................gxttgtstgtmt.",
        "...................gmttssttsmg..",
        "...................gxtggttmsw...",
        "...................cxmttsstc....",
        "....................smmmsc......",
        "....................ccccc.......",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
    ])

    // Full blink, tail returns right.
    static let idle2 = frameFlipped([
        ".wgpwccwwwcpggtggccwwpcwctcwcgww",
        ".wgscwwwwpggtttttggcwwwcgggcwwwc",
        "wgtmtcwwcggttttttttgcwwggpgpwwgg",
        "ctgcpcwpttssstggtttssgpcwwwccgss",
        ".ctcwwwcgtsmxxsttsmxmttgcccgttsx",
        "..gscwwwcgtttmxxxxxsttttttttttts",
        ".wtsgwwwwcgttttttstttttttttttttt",
        ".ctgcwwwwcggtttttttttttttttttttt",
        "..ctcwwwwcpggttttttttttttttttttt",
        "...ggcwwwwcpggtttttttttttttttttt",
        "...csgwwwwwcpgggtttttttttttttttt",
        "....gmpwwwwwcpgggttttggtttttggtt",
        "...wgxtcwwwwwccpggttggggtttggggt",
        "...gmxsgcwwwwwwcppttgppggtgggpgt",
        "...sxssmtcwwwwwwwcggpcppgtggppgg",
        "...gxmtmscwwwwwwwcgpcccpggpppccg",
        "...sxmmtsgcwwwwwwwccwccppgppccwc",
        "...gmmmgttgcwwwwwwwwwwcccpcccwww",
        "....mmtpptmtgcwwwwwwwwwcwcwcwwww",
        "....mmgpppsmggcwwwwwwwwwwwwwwwww",
        "....mmgppcggptscwwwwwwwwwwwwwwww",
        "....mmgppcccctxtgcwwwwwwwwwwwwww",
        "....mmgppppcctmttgcwwwwwwwwwwwww",
        "....mstgpppctmsttssgccwwcccwwccg",
        "....mmsgpppgmmttsmmsttccgggcptts",
        "....tmsgppgssttsxtcwcgtggcgggccw",
        "....wmstttstttmmtw....cc...cc...",
        ".....mstsmsttmmgw...............",
        ".....xstsstsmsgw................",
        ".....xmttssssc..................",
        ".....sxmmsgcc...................",
        ".....csssg......................",
        "......ccc.......................",
        "................................",
    ])

    // Half-lidded stare, tail lifted.
    static let idle3 = frameFlipped([
        ".ctmcwwwcgggtgggggtcwwcttgww.ctg",
        "ctgtgwwcggttgcgiiigtc.cpppc.gtgi",
        "ctcwcwwgtttgwgibbiittgcwwwctstii",
        ".ctgwwwwgsstwitxxsimtttggggtsbis",
        "..smpwwwctxxsxsxxxxxttttttttmxsx",
        ".gtgcwwwwgtmxxxmmmxmttttttttsxxx",
        ".wtgwwwwwcggtttttttttttttttttttt",
        "..ctcwwwwcgggttttttttttttttttttt",
        "...gtwwwwwcggttttttttttttttttttt",
        "...wmgwwwwwcgttttttttttttttttttt",
        "....cxpwwwwwwpgtttttggtttttggttt",
        "...cxmtcwwwwwwcppgtgppggtggppgsg",
        "...mmttmpwwwwwwwcttpccpgtggccgtt",
        "...gxttmgcwwwwwwcgpccccggpccccgg",
        "...sxmsttpwwwwwwwccwccccpcccwccw",
        "...tmmsgttgwwwwwwwwwwccccccwwwww",
        "....xmgppsstcwwwwwwwwwwwcwcwwwww",
        "....xspppgmtggwwwwwwwwwwwwwwwwww",
        "....xmppccpcgmgwwwwwwwwwwwwwwwww",
        "....xmpppcwcpmsgcwwwwwwwwwwwwwww",
        "....xsgppgpccmsttpwwwwwwwwwwwwcc",
        "....xsspppcpsmggtmtcwwwwwwwwwcss",
        "....mmsgpppgmtggmxmmtcctsgcgssxx",
        "....cxtgppgmtggmxw.wcstcwgstcw.c",
        "....cxssggmtgtmxc.....w...w.....",
        "....cxssmmtgtmmc................",
        "....cxsttgtsmc..................",
        "....wxmggtmmc...................",
        ".....cxxxxt.....................",
        "......gggg......................",
        "................................",
        "................................",
        "................................",
        "................................",
    ])

    // Alert perk, derived from the ear-flick keyframe without the external accent marks.
    static let idle4 = frameFlipped([
        "..tgwwwwwcpgggttttgcwwwwcgcwwwwc",
        ".ctmtcwwwgggttgggggtcwwctggcwwct",
        "ctggtpwcggtttgcciitgtcwcccccwcgg",
        "wggcccwcttttgcgiiiiittgcwwwcgtti",
        "..gtcwwwpgtsscbimxiimttgggggttxi",
        "..gmgwwwwpgmmcbbxxbbxtttttttttxb",
        ".gtgpcwwwcgsxbbttxxbxtttttttttxb",
        "..gtcwwwwcgtmxsc.sxxmtttttttttms",
        "...tpwwwwwcgtsxmgxxxtttttttttttx",
        "...cscwwwwwcgtsxxxxttttttttttttt",
        "....mtcwwwwcpgtttttttttttttttttt",
        "....gxtcwwwwwcggtttttggtttttggtt",
        "...csxsgcwwwwwccggttgpgggtgggpgt",
        "..cxxmsmtcwwwwwwcpttgppggtggppgt",
        "..wgmmtmmcwwwwwwwgggpccpgggppppg",
        "..wtxmmstgcwwwwwwcppccccpgpcpccp",
        "..wtmmmtgtgwwwwwwwwwwwcccpcpcwww",
        "....xxsgptsgcwwwwwwwwwccccccwwww",
        "....xmgppptmtccwwwwwwwwwwwwwwwww",
        "....xmgpppggcgtcwwwwwwwwwwwwwwww",
        "....xsgppcwwctxgccwwwwwwwwwwwwww",
        "....xsgppgppcgmstgcwwwwwwwwwwwww",
        "....xstgpppcgmsttstgwwwwwwwwwwcg",
        "....xstgppppmmtttxxmttccgtgwpttm",
        "....xmttppptmtttmsccggtttgtttggc",
        "....cxsstgsmttsxsw....cc..wgc...",
        ".....xssmmmtgsxmw...............",
        "....wxstsmttmxg.................",
        "....wxstttsxxc..................",
        ".....mmstmmgc...................",
        ".....cxxxmc.....................",
        "......cccw......................",
        "................................",
        "................................",
    ])

    // Centered blink.
    static let idle5 = frameFlipped([
        ".......gtpccccwwwwccccwcwwwcspcg",
        ".......ctgwwwwwwwcpgttggccwwcw.c",
        "........gsgwwwwwcpgttttgggcwwwct",
        "......wgtstcwwccgttttttttggcwhgp",
        "......ctgcccwwgttsmstgggttssgcww",
        ".......cgpwwwwgttsxxmtssmxxmttgc",
        "........gsgwwwwpgttmxxxxxxmttttt",
        ".......cgttcwwwcggtttttttttttttt",
        ".......ctgccwwwwcgtttttttttttttt",
        "........ctpwwwwwcggttttttttttttt",
        ".........ggcwwwwcpggtttttttttttt",
        "..........tgwwwwwccggttttttttttt",
        "..........csgwwwwwwcgtttttttgttt",
        "..........wmmcwwwwwwcggttttgpgtt",
        ".........wsxmtcwwwwwwccppttgcggg",
        ".........smttsscwwwwwwwcgtgpccpg",
        ".........cmmttmpwwwwwwwwpgpccccg",
        ".........gmmstggcwwwwwwwwccwcccc",
        ".........tmmmtgtgcwwwwwwwwwwwccc",
        "..........tmsgppmtgcwwwwwwwwwccw",
        "..........tmtpppgmmgcwwwwwwwwwww",
        "..........tmtpppgtcgsgwwwwwwwwww",
        "..........tmtppcw.cpmmgcwwwwwwww",
        "..........tmtppgppccmstgpwwwwwww",
        "..........tmtgpppccgmttttgcwwwww",
        "..........tmstppcpgmsgggmxtgcwcg",
        "..........cmstppppsmgggmsgtttggt",
        "...........smtgpptstgtmmw...ctg.",
        "...........sststssggtmmc........",
        "...........smtsmsggsmsw.........",
        "...........smtgggsmmc...........",
        "...........txtggmxsc............",
        "...........cxxxxmc..............",
        "............cgggc...............",
    ])

    // Centered bright-eyed pose.
    static let idle6 = frameFlipped([
        ".......gtccccwwwwwcppcccwwwctcct",
        ".......ctgwwwwwwcpggttttgcwccwwg",
        "........gsgwwwwcggtttggggtc.wwgt",
        "......cgtstcwwcpgttgcwcccggcwwgp",
        "......gtccccwcgttttcwiiiicgtgcww",
        "......wggcwwwcgttsgwiitbiigtttgc",
        "........tspwwwcgtxmciixxbibstttt",
        ".......csstcwwwcgmmibbxxxbxstttt",
        ".......gtgcwwwwcgsxbbccmxbxstttt",
        "........gtcwwwwwptsxxgwsxxmttttt",
        ".........ggcwwwwcgtsxxmxxxsttttt",
        ".........wsgwwwwwcgtsxxxxstttttt",
        "..........gspwwwwwcgttttttttgttt",
        "..........cxtcwwwwwcggtttttgpgtt",
        ".........cmxmgcwwwwwwcccgstgcggt",
        ".........smttmtcwwwwwwwcttgccpgt",
        ".........cmmtmtcwwwwwwwcgpccccpg",
        ".........gmxmttgcwwwwwwwcccwcccp",
        ".........tmmmttsgcwwwwwwwwwwwccc",
        "..........sxtgptmtgcwwwwwwwwwcwc",
        "..........smgppptmsgcwwwwwwwwwww",
        "..........smgpppggcgscwwwwwwwwww",
        "..........smtppcwwcgxtccwwwwwwww",
        "..........smgpppppcpmstgcwwwwwww",
        "..........smtgpppccgmttttgcwwwww",
        "..........smsgppcpgxtggtxxtgcwcg",
        "..........gmstpppgssggtmmggttggt",
        "...........sstgppssggtxxw...ctg.",
        "...........ssttttsggtmmc........",
        "...........sstsmsggsxt..........",
        "...........smtgggtxxg...........",
        "...........txtggsmsc............",
        "...........wxxxxxg..............",
        "............cgggc...............",
    ])

    // Tail sweep back into frame.
    static let idle7 = frameFlipped([
        "......gtccccwwwwwcgggccwwwwtgccs",
        "......wtgwwwwwwcggggtttgpwwcwwct",
        ".......gmgwwwwcgggttggggggwwwctt",
        ".....cttstcwwcpgtttpccccgggw.ggp",
        ".....ctccccwcgtttgchiiiiigtgcw.h",
        "......ggcwwwwgtttswiitsiiisttgcp",
        ".......tsgwwwwgtsxciixxxibxttttt",
        "......cttgcwwwcgsxgbbxxxxbxttttt",
        "......ctgcwwwwwgtmbbgwtxxbxttttt",
        ".......ctcwwwwwcgtmxt.gxxxtttttt",
        "........ggwwwwwcggtmxsxxxmtttttt",
        "........wmgwwwwwcggtmxmmmttttttt",
        ".........gmgwwwwwcpgtttttttgtttt",
        ".........cxscwwwwwwpggttttgpgttt",
        "........cxxsgcwwwwwwwcpgttgcggtt",
        ".......cmmtgsscwwwwwwwcgtgcccpgt",
        "........cxmtsspwwwwwwwwcppccccgt",
        ".......wtxmmtggcwwwwwwwwccwcccpp",
        ".......wtmmmtgsgcwwwwwwwwwwwcccc",
        ".........sxsgpgmtgcwwwwwwwwwccwc",
        ".........smtppptmmgcwwwwwwwwwwww",
        ".........smtpppggcpsgwwwwwwwwwww",
        ".........sxtppcw.cpxmgcwwwwwwwww",
        ".........smtppgppccmstggwwwwwwww",
        ".........smtgpppccgmtgttgcwwwwww",
        ".........mmstppcppmstgtmxsgpwwgg",
        ".........gmmtppppsmtggmmgtttggtt",
        "..........smtgpptmtgtmxc...ctg..",
        "..........smtstssggtmxc.........",
        "..........smttssggsxmc..........",
        "..........smtgggtmmg............",
        "..........gmsggsxmc.............",
        "...........sxxxxg...............",
        "...........cgggc................",
    ])

    // Loop back to the bright open-eyed pose.
    static let idle8 = frameFlipped([
        "..ggwwwwwcpgggtttgcwwwwwggwwwwwc",
        ".ctmgwwwcgggttgppgggwwwgtggwwwct",
        "ctgttcwcggtttgwgiitggwwcccpwwctg",
        "wtgcccwpttttgwiiiiittgpwwwwcgtti",
        "..ggwwwcgttmggiibbibxttgggggtsmi",
        "..tmgwwwcggxtibbxxbbxtttttttgsxb",
        ".gtgpwwwwcgmxbbtsxxbxgttttttgsxb",
        "..ggwwwwwcgtmxg.wmxxstttttgggtxg",
        "..ctcwwwwwgttmxtsxxmgttttttttgsx",
        "...gscwwwwcgttmxxxmttttttttttttt",
        "...cxgcwwwwcggtttttttttttttttttt",
        "....gxpwwwwwcggtttttgggtttttggtt",
        "...cmxtcwwwwwwcgggttgpggttggpgtt",
        "..cxxsssgwwwwwwwcgtgpcpggtggppgt",
        "..wgmstmtcwwwwwwwggpcpcpggppppgg",
        "..wtxmsstgwwwwwwwcpcccppggccpccp",
        "..cmmmmgttccwwwwwwwwwwccppcpcwww",
        "....xmtgpstpcwwwwwwwwwccccccwwww",
        "...wxsgppgmmgcwwwwwwwwwwwwwwwwww",
        "...wxtpppptgptgwwwwwwwwwwwwwwwww",
        "...wxtgpcwwwcmmgcwwwwwwwwwwwwwww",
        "...wxtppgppcwsmttgcwwwwwwwwwwwww",
        "...wxttppppcgmtttstcwwwwwwwwwwwg",
        "...wxtsgpppgmsttsxxmtgwcgtcwgtsx",
        "...wxssgppgmsttsxtccgtttggtttggc",
        "....gmttpgmsttmxt....cgc..cgc...",
        "....cxtssmstgmxt................",
        "....cxtsmmttmxg.................",
        "....cxsttttxxg..................",
        "....cxmttmscc...................",
        ".....mxxxg......................",
        ".....cggc.......................",
        "................................",
        "................................",
    ])

    // Side walk, left paw forward.
    static let walk0 = frame([
        "........................",
        "........................",
        ".............xx.........",
        "...........xxssxx.......",
        "..........xspccpsx......",
        ".........xspccccssx.....",
        "........xsscccccccsx....",
        ".......xccccggggccccx...",
        "......xcccggggggggcccx..",
        "......xccggxxbbixxgccx..",
        ".....xcccggxbihbxxgccx..",
        ".....xccccggxbbxxgcccx..",
        ".....xccccgggppggcccgx..",
        "....xccccccggggggccccsx.",
        "....xcccwwwwwwwwwwcccsx.",
        "...xcccwwwwwwwwwwwwwccx.",
        "...xcccwwwwwwwwwwwwwwwx.",
        "...xcccwwwwwwwwwwwwccsx.",
        "...xccccwwwwwwwwwwccssx.",
        "....xcccwwwwwwwwcccstx..",
        "....xcccww....wwccsttx..",
        ".....xtt......wwccctx...",
        "......xt.......tttxx....",
        "......xx........xx......",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
    ])

    // Side walk, right paw forward.
    static let walk1 = frame([
        "........................",
        "........................",
        ".............xx.........",
        "...........xxssxx.......",
        "..........xspccpsx......",
        ".........xspccccssx.....",
        "........xsscccccccsx....",
        ".......xccccggggccccx...",
        "......xcccggggggggcccx..",
        "......xccggxxbbixxgccx..",
        ".....xcccggxbihbxxgccx..",
        ".....xccccggxbbxxgcccx..",
        ".....xccccgggppggcccgx..",
        "....xccccccggggggccccsx.",
        "....xcccwwwwwwwwwwcccsx.",
        "...xcccwwwwwwwwwwwwwccx.",
        "...xcccwwwwwwwwwwwwwwwx.",
        "...xcccwwwwwwwwwwwwccsx.",
        "...xccccwwwwwwwwwwccssx.",
        "....xstcccwwwwwwwwcccx..",
        "...xttsccww....wwcccx...",
        "....xctccww.....tttx....",
        ".....xxttt.......tx.....",
        "......xx........xx......",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
    ])

    // Curled sleeping pose.
    static let sleep0 = frame([
        "........................",
        "........................",
        "........................",
        "........................",
        "........xxxxxxxx........",
        "......xxssppssxx........",
        ".....xsccccccccsxxx.....",
        "....xccccggggccccccx....",
        "...xcccgggxxxxgggcccx...",
        "...xcccggxbbxxbbxgccx...",
        "...xccccggggppgggcccx...",
        "..xccccccggggggggccccx..",
        "..xcccwwwwwwwwwwwwcccx..",
        ".xcccwwwwwwwwwwwwwwwccx.",
        ".xcccwwwwwwwwwwwwwwcccx.",
        ".xcccwwwwwwwwwwwwcccttx.",
        ".xccccwwwwwwwwccccttttx.",
        ".xgccccwwwwccccccttttx..",
        "..xggcccccccccccttttx...",
        "...xcccccccccccctttx....",
        "....xxxxxxxxxxxxxxx.....",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
    ])

    // Sleeping breathing, slightly puffed body.
    static let sleep1 = frame([
        "........................",
        "........................",
        "........................",
        "........................",
        "........xxxxxxxx........",
        "......xxssppssxx........",
        ".....xsccccccccsxxx.....",
        "....xccccggggccccccx....",
        "...xcccgggxxxxgggcccx...",
        "...xcccggxbbxxbbxgccx...",
        "...xccccggggppgggcccx...",
        "..xccccccggggggggccccx..",
        "..xcccwwwwwwwwwwwwcccx..",
        ".xcccwwwwwwwwwwwwwwwwcx.",
        ".xcccwwwwwwwwwwwwwwwccx.",
        ".xcccwwwwwwwwwwwwwccttx.",
        ".xccccwwwwwwwwccccttttx.",
        ".xgccccwwwwcccccctttttx.",
        "..xggccccccccccctttttx..",
        "...xccccccccccccttttx...",
        "....xxxxxxxxxxxxxxx.....",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
    ])

    // Front happy jump with paws spread.
    static let jump = frame([
        "........................",
        "........................",
        "........xx......xx......",
        ".......xssx....xssx.....",
        "......xsppsx..xsppsx....",
        "......xspcpxxxspcpsx....",
        ".....xssccccccccccssx...",
        ".....xsccccggggccccsx...",
        "....xccccggggggggccccx..",
        "....xcccgggxxxxgggcccx..",
        "...xcccggxbbixxibbxgccx.",
        "...xcccggxbihxxhibxgccx.",
        "...xcccggxxbbxxbbxxgccx.",
        "...xccccgggggppggggcccx.",
        "....xccccgggpxxpggccx...",
        ".xx..xccccccccccccccx.xx",
        "xtxx.xgcccwwwwwwcccgxxtx",
        "xtttxxgccwwwwwwwwccggttx",
        ".xtttxcccwwwwwwwwccccctx",
        "..xcccwwwwwwwwwwwwwwccx.",
        "..xcccwwwcwwwwcwwwcccx..",
        "...xcccwwwwwwwwwwcccx...",
        "...xcttw........wttcx...",
        "....xxt..........txx....",
        ".....xt..........tx.....",
        ".....xx..........xx.....",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
    ])

    static let idleFrames = [idle0, idle1, idle2, idle3, idle4, idle5, idle6, idle7, idle8]
    static let walkFrames = [walk0, walk1]
    static let sleepFrames = [sleep0, sleep1]
    static let jumpFrames = [jump]
}

// MARK: - NSColor Hex Extension
extension NSColor {
    convenience init?(hex: UInt, alpha: CGFloat = 1.0) {
        self.init(
            red: CGFloat((hex >> 16) & 0xFF) / 255.0,
            green: CGFloat((hex >> 8) & 0xFF) / 255.0,
            blue: CGFloat(hex & 0xFF) / 255.0,
            alpha: alpha
        )
    }
}
